// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTuY-NZ1EyaL9fDrM4lFaTTpRIdrOJSE8',
    appId: '1:881636060815:web:eadf4ea58b29d0feb70afa',
    messagingSenderId: '881636060815',
    projectId: 'clean-arch-chat',
    authDomain: 'clean-arch-chat.firebaseapp.com',
    storageBucket: 'clean-arch-chat.appspot.com',
    measurementId: 'G-P9HXDT1FQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgBG3bWHvCjurP7RBsqsvNnt03y3QXVrU',
    appId: '1:881636060815:android:c1fa7244eb940fc3b70afa',
    messagingSenderId: '881636060815',
    projectId: 'clean-arch-chat',
    storageBucket: 'clean-arch-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPZmLRcJ6o6GWUFKijWxhccew6zcBUqAQ',
    appId: '1:881636060815:ios:c668a65c79505f5db70afa',
    messagingSenderId: '881636060815',
    projectId: 'clean-arch-chat',
    storageBucket: 'clean-arch-chat.appspot.com',
    iosClientId: '881636060815-7stlk2hpv01b8uv1gmalq16incne1kot.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArchChat',
  );
}
